apiVersion: apps/v1
kind: Deployment
metadata:
  name: konsign-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konsign-api
  template:
    metadata:
      labels:
        app: konsign-api
    spec:
      containers:
      - name: konsign-api
        image: razdeep/konsign-api:$IMAGE_TAG
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PROFILE
          value: dev